### ISSUE TITLE
Npm va yarn install da lock fayllar

### ISSUE THREAD

**Issue by shaxzodbek-uzb** [shaffof-devs/mahalla_backend#2]
Npm install qilinganda package-lock.json update qilyapti. yarn install qilinganda yarn.lock fileni yaratyapti. Nima yechim qilamiz bu uchun. Install qilishni boshqacha usulda qilish kerakmi yoki?

**Comment by max-17** [comment]
> As of Yarn 1.7.0, you can import your package-lock.json state, generated by npm to Yarn, by using yarn import.

https://classic.yarnpkg.com/lang/en/docs/migrating-from-npm/

'yarn import' qilsanggiz package-lock.json dagi narsalani yarn.lock ga import qiladi keyin guthub ga shuni yuklaysiz
